### ISSUE TITLE
Tracking issue for installation/removal instructions 

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#16]
Implementation concerns:

* [ ] Download instructions (`instruction.sh`) when downloading the package's data 
* [ ] Keep the instructions in a local cache so removal can be done offline
* [ ] Implement some (optional) shell callbacks in `instruction.sh`:
  * [ ] `before_installation`: called before the package's files are unwrapped
  * [ ] `after_installation`: called after the package's files are unwrapped
  * [ ] `before_removal`: called before the package's files are removed
  * [ ] `after_removal`: called after the package's files are unwrapped

These callbacks will allow a package to execute some extra steps at specific times, like starting a daemon or continue the installation in ways that cannot be expressed by moving files.

More callback may come.
