### ISSUE TITLE
Tracking issue for groups implementation

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#17]
Nest is a requirement-based package manager, and groups are an important part of them. A user must be able to:

* [ ] Add a new group with an unique name
* [ ] Remove a group given it's name
  * [ ] If the group isn't empty, an error must be thrown
  * [ ] It must still be possible to "force" the removal of the group (and therefore it's content)
* [ ] Add a requirement to a group, given the group's name and the requirement
* [ ] Remove a requirement of a group, given the group's name and the requirement
* [ ] Any node of the dependecy graph can be dependant of a group, and therefore, of it's dependencies (recursively)
