### ISSUE TITLE
Tracking issue for available sub-commands 

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#18]
This issue tracks all sub-commands required for Nest 0.1.0:

The following sub-commands are required:

* [ ] `requirement`: Manages requirements
  * [ ] `add`: Adds a requirement to a group (default: `@root`)
  * [ ] `remove`: Removes a requirement of a group (default: `@root`)
  * [ ] `update`: Updates all requirement's filler of the given node (recursively) (default: `@root`), fulfilling empty requirements
* [ ] `group`: Manages groups
  * [ ] `create`: Creates a new group as a child of the given group (default: `@root`)
  * [ ] `delete`: Deletes an existing group (if empty, otherwise a `-f`, `--force` flag can make it remove its content recursively)
  * [ ] `list`: Lists all existing groups
* [ ] `repository`: Manages repositories
  * [ ] `list`: Lists all repositories
  * [ ] `pull`: Pull the given repositories, or all of them if none is given
* [ ] `graph`: Shows a user-friendly representation of the dependency graph
* [ ] `merge`: A two-steps sub-command:
    * Fulfills empty requirements of the wanted dependency graph (made with commands like `nest requirement add` etc.).
    * Generates and apply all transactions needed to go from the current dependency graph (the one matching the file-system) to the wanted dependency graph.

These sub-commands are shortcuts for the `training-wheels` mode:

* [ ] `pull`: shortcut to `nest repository pull`
* [ ] `install`: shortcut to `nest requirement add && nest merge`
* [ ] `uninstall`: shortcut to `nest requirement remove && nest merge`
* [ ] `upgrade`: shortcut to `nest requirement update && nest merge`
