### ISSUE TITLE
Tracking issue for Nest 0.1.0

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#20]
Tracking issues for Nest 0.1.0:

* [ ] Implementation of sub-commands (See #18)
* [ ] Groups (See #17)
* [ ] Instructions for installation/removal (See #16)
* [ ] Training-wheels mode (See #19)
