### ISSUE TITLE
Tracking issue for pulling repositories

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#22]
Tracking issues for pulling repositories.

Check list:
* [x] Manage list of repositories obtained from a configuration file
* [x] Download the list of available packages from a repository
* [x] Store a local copy of this list for offline research
