### ISSUE TITLE
Tracking issue for configuration file

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#23]
Tracking issue for Nest's configuration file

Check list:
* [x] Follows TOML format
* [x] Contains a list of repositories
  * [x] Name
  * [x] URL
* [x] Contains optional path to
  * [x] Where pulled packages are cached
  * [x] Where installed packages metadatas are cached
  * [x] Where the dependency graph is stored
