### ISSUE TITLE
Tracking issue for managing requirements

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#24]
Check list:

Adding requirements:
* [x] Test if the given requirement can be fulfilled
  * [x] Warn if not
* [x] Add the requirement to the dependency graph

Removing requirements:
* [x] Test if the given node has the given requirement
  * [x] Error if not
* [x] Remove the requirement of the dependency graph
