### ISSUE TITLE
Tracking issues for merging the dependency graph

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#25]
Check list:

* [x] Subtract the scratch dependency graph from the merged dependency graph
  * [x] Extract a list of transactions (INSTALL, UPDATE, REMOVE)
* [x] Execute the transactions in order
* [x] Save the scratch dependency graph as the new merged dependency graph

As a temporary fallback, waiting for `nest fix` and `nest rollback`, we'll save the dependency graph even if the installation failed.
