### ISSUE TITLE
Tracking issues for nest-cli

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#26]
Check list:

* [x] Flag  `--chroot <path>` that indicates the target repository
* [x] Subcommand `requirement` that manages the scratch dependency graph's requirements
  * [x] Command `add <REQUIREMENT>...`: adds requirement(s) to the scratch dependency graph
  * [x] Command `remove <REQUIREMENT>...`: removes requirement(s) of the scratch dependency graph
* [x] Command `pull [REPOSITORY]...`: pulls the given repositories, or all of them if none are given.
* [x] Command `merge`: merges the scratch dependency graph with the targeted system.
