### ISSUE TITLE
Tracking issues for Nest v0.1.0

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#27]
Check list:

* [x] Basic commands for nest-cli (See #26 )
* [x] Manage the configuration file (See #23 )
* [x] Pull repositories (See #22 )
* [x] Add requirements (See #24 )
* [x] Remove requirements (See #24 )
* [x] Merge the scratch dependency graph with the system (See #25 )
